- name: copy file for deployment
  hosts: apache
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: webapp/target/webapp.war
        dest: /var/       
        mode: 0644
